export { Login } from './login'
export { NotFound } from './not-found'
export { Pannel } from './pannel'
export { LeaveIndex, LeaveDetail, PersonnelLeaveIndex } from './leave'
export { Profile } from './profile'
export { Personnels, CreatePersonnel, PersonnelDetail } from './personnel'
export { CreateTrain, TrainsIndex, AttendTrain } from './training'
